# This file is automatically generated by https://github.com/livecycle/preevy/blob/main/packages/cli/scripts/homebrew.js
# Do not update this file directly; Please update the template instead
class Preevy < Formula
  desc "Quickly deploy preview environments to your cloud provider or Kubernetes cluster"
  homepage "https://preevy.dev"
  url "https://github.com/livecycle/preevy/releases/download/v0.0.63/preevy-v0.0.63-darwin-x64.tar.gz"
  sha256 "b0c3f53de8789f20f0e49f515bcbb6e4a7958cd0fe95f3d7b9173f7929d123cf"
  license "Apache-2.0"
  version "0.0.63"

  on_macos do
    on_arm do
      url "https://github.com/livecycle/preevy/releases/download/v0.0.63/preevy-v0.0.63-darwin-arm64.tar.gz"
      sha256 "a9addf18b501709df8a8804491dbaa0ade775ba67ba9ea2b43cda940aea63e9f"
    end
  end

  on_linux do
    url "https://github.com/livecycle/preevy/releases/download/v0.0.63/preevy-v0.0.63-linux-x64.tar.gz"
    sha256 "2774ee73d551f20f4f628e87c411d37c904dd64b1b0ae832b6785fa0c42f27a3"
    on_arm do
      url "https://github.com/livecycle/preevy/releases/download/v0.0.63/preevy-v0.0.63-linux-arm64.tar.gz"
      sha256 "7cf753a98b9e8a67655288b85fecc9e4cb98f906650026a2a3f0fd973051e926"
    end
  end

  def install
    inreplace "bin/preevy", /^CLIENT_HOME=/, "export PREEVY_OCLIF_CLIENT_HOME=#{lib/"client"}
CLIENT_HOME="
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/preevy"
  end

  test do
    system bin/"preevy", "version"
  end
end

