# This file is automatically generated by https://github.com/livecycle/preevy/blob/main/packages/cli/scripts/homebrew.js
# Do not update this file directly; Please update the template instead
class Preevy < Formula
  desc "Quickly deploy preview environments to your cloud provider or Kubernetes cluster"
  homepage "https://preevy.dev"
  url "https://github.com/livecycle/preevy/releases/download/v0.0.60/preevy-v0.0.60-darwin-x64.tar.gz"
  sha256 "4384e5b86cd695f0c360583e04ae47845211e616b871ea94a63b878cd48ec316"
  license "Apache-2.0"
  version "0.0.60"

  on_macos do
    on_arm do
      url "https://github.com/livecycle/preevy/releases/download/v0.0.60/preevy-v0.0.60-darwin-arm64.tar.gz"
      sha256 "064ef2d851b1a83dbb93cc3ac22e01c502a18b068e9cb4164cff13f2f9911984"
    end
  end

  on_linux do
    url "https://github.com/livecycle/preevy/releases/download/v0.0.60/preevy-v0.0.60-linux-x64.tar.gz"
    sha256 "0e614223c0be54771f090d373378af627b8dc9e7328c7a9c683cbc79cfb58070"
    on_arm do
      url "https://github.com/livecycle/preevy/releases/download/v0.0.60/preevy-v0.0.60-linux-arm64.tar.gz"
      sha256 "63868c07a7eeeb8d634915ea736825018d1a9f9641726193305617d533324364"
    end
  end

  def install
    inreplace "bin/preevy", /^CLIENT_HOME=/, "export PREEVY_OCLIF_CLIENT_HOME=#{lib/"client"}
CLIENT_HOME="
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/preevy"
  end

  test do
    system bin/"preevy", "version"
  end
end

