# This file is automatically generated by https://github.com/heroku/cli/blob/main/scripts/release/homebrew.js
# Do not update this file directly;
# Please update the template instead:
# https://github.com/heroku/cli/blob/main/scripts/release/homebrew/templates/heroku.rb
class Preevy < Formula
  desc "Quickly deploy preview environments to your cloud provider or Kubernetes cluster"
  homepage "https://preevy.dev"
  url "https://releases.preevy.dev/versions/0.0.59/f2b1f88/preevy-v0.0.59-f2b1f88-darwin-x64.tar.gz"
  sha256 "2edd0ed5f1ea6ef430f69d004f0bb46cce65b0833bc9593211ce203dcb25a22e"
  license "Apache-2.0"
  version "0.0.59"

  on_macos do
    on_arm do
      url "https://releases.preevy.dev/versions/0.0.59/f2b1f88/preevy-v0.0.59-f2b1f88-darwin-arm64.tar.gz"
      sha256 "2edd0ed5f1ea6ef430f69d004f0bb46cce65b0833bc9593211ce203dcb25a22e"
    end
  end

  on_linux do
    url "https://releases.preevy.dev/versions/0.0.59/f2b1f88/preevy-v0.0.59-f2b1f88-linux-x64.tar.gz"
    sha256 "2edd0ed5f1ea6ef430f69d004f0bb46cce65b0833bc9593211ce203dcb25a22e"
  end

  def install
    inreplace "bin/preevy", /^CLIENT_HOME=/, "export PREEVY_OCLIF_CLIENT_HOME=#{lib/"client"}\nCLIENT_HOME="
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/preevy"
  end

  test do
    system bin/"preevy", "version"
  end
end
